language: node_js
node_js:
 - "stable"
install: npm install
services:
- postgresql
env:
- DB_USER=jhaastrup DB_PASSWORD=null DB_NAME=bookameal_test
script: npm test
before_script:
- psql -c 'drop database if exists mealbookingtest;' -U postgres
- psql -c 'create database bookameal_test;' -U postgres
- psql -c "CREATE USER jhaastrup WITH PASSWORD 'null';" -U postgres
- npm run migrate
after_success: npm run coverage
